name: Build on PR

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Build
        run: |
          mkdir -p dist
          GOOS=windows GOARCH=amd64 go build \
          -ldflags="-s -w" \
          -o dist/tt-windows-amd64.exe  ./cmd/time-tracker
