# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - 'v*' # z.B. v1.2.3

jobs:
      
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Extract version info
      id: vars
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        COMMIT=$(git rev-parse --short HEAD)
        BUILD_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "commit=$COMMIT" >> $GITHUB_OUTPUT
        echo "build_time=$BUILD_TIME" >> $GITHUB_OUTPUT

    - name: Build
      run: |
        mkdir -p dist
        GOOS=windows GOARCH=amd64 go build \
        -ldflags="-s -w \
        -X github.com/LReg/time-tracker/internal/version.Version=${{ steps.vars.outputs.version }} \
        -X github.com/LReg/time-tracker/internal/version.Commit=${{ steps.vars.outputs.commit }} \
        -X github.com/LReg/time-tracker/internal/version.Date=${{ steps.vars.outputs.build_time }}" \
        -o dist/tt-windows-amd64.exe  ./cmd/time-tracker
        
        GOOS=darwin GOARCH=arm64 go build \
        -ldflags="-s -w \
        -X github.com/LReg/time-tracker/internal/version.Version=${{ steps.vars.outputs.version }} \
        -X github.com/LReg/time-tracker/internal/version.Commit=${{ steps.vars.outputs.commit }} \
        -X github.com/LReg/time-tracker/internal/version.Date=${{ steps.vars.outputs.build_time }}" \
        -o dist/tt-darwin-arm64-M1  ./cmd/time-tracker
        
        GOOS=darwin GOARCH=amd64 go build \
        -ldflags="-s -w \
        -X github.com/LReg/time-tracker/internal/version.Version=${{ steps.vars.outputs.version }} \
        -X github.com/LReg/time-tracker/internal/version.Commit=${{ steps.vars.outputs.commit }} \
        -X github.com/LReg/time-tracker/internal/version.Date=${{ steps.vars.outputs.build_time }}" \
        -o dist/tt-darwin-amd64-M1  ./cmd/time-tracker
        
        GOOS=darwin GOARCH=amd64 go build \
        -ldflags="-s -w \
        -X github.com/LReg/time-tracker/internal/version.Version=${{ steps.vars.outputs.version }} \
        -X github.com/LReg/time-tracker/internal/version.Commit=${{ steps.vars.outputs.commit }} \
        -X github.com/LReg/time-tracker/internal/version.Date=${{ steps.vars.outputs.build_time }}" \
        -o dist/tt-darwin-amd64  ./cmd/time-tracker
        
        GOOS=linux GOARCH=arm64 go build \
        -ldflags="-s -w \
        -X github.com/LReg/time-tracker/internal/version.Version=${{ steps.vars.outputs.version }} \
        -X github.com/LReg/time-tracker/internal/version.Commit=${{ steps.vars.outputs.commit }} \
        -X github.com/LReg/time-tracker/internal/version.Date=${{ steps.vars.outputs.build_time }}" \
        -o dist/tt-linux-arm64  ./cmd/time-tracker
        
        GOOS=linux GOARCH=amd64 go build \
        -ldflags="-s -w \
        -X github.com/LReg/time-tracker/internal/version.Version=${{ steps.vars.outputs.version }} \
        -X github.com/LReg/time-tracker/internal/version.Commit=${{ steps.vars.outputs.commit }} \
        -X github.com/LReg/time-tracker/internal/version.Date=${{ steps.vars.outputs.build_time }}" \
        -o dist/tt-linux-amd64  ./cmd/time-tracker
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: "Release ${{ steps.vars.outputs.version }}"
        tag_name: ${{ steps.vars.outputs.version }}
        files: |
          dist/tt-windows-amd64.exe
          dist/tt-darwin-arm64-M1
          dist/tt-darwin-amd64
          dist/tt-linux-amd64
          dist/tt-linux-arm64
